/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 39.4.5 Sun May  5 03:28:49 2024.
 */

#include <string.h>

#include "mppt.h"

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t pack_right_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint32_t unpack_left_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) << shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

static inline uint32_t unpack_right_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) >> shift);
}

int mppt_mg0_status_pack(
    uint8_t *dst_p,
    const struct mppt_mg0_status_t *src_p,
    size_t size)
{
    uint32_t mg0_input_current;
    uint32_t mg0_input_voltage;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    memcpy(&mg0_input_current, &src_p->mg0_input_current, sizeof(mg0_input_current));
    dst_p[0] |= pack_left_shift_u32(mg0_input_current, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(mg0_input_current, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(mg0_input_current, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(mg0_input_current, 24u, 0xffu);
    memcpy(&mg0_input_voltage, &src_p->mg0_input_voltage, sizeof(mg0_input_voltage));
    dst_p[4] |= pack_left_shift_u32(mg0_input_voltage, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(mg0_input_voltage, 8u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(mg0_input_voltage, 16u, 0xffu);
    dst_p[7] |= pack_right_shift_u32(mg0_input_voltage, 24u, 0xffu);

    return (8);
}

int mppt_mg0_status_unpack(
    struct mppt_mg0_status_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t mg0_input_current;
    uint32_t mg0_input_voltage;

    if (size < 8u) {
        return (-EINVAL);
    }

    mg0_input_current = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    mg0_input_current |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    mg0_input_current |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    mg0_input_current |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    memcpy(&dst_p->mg0_input_current, &mg0_input_current, sizeof(dst_p->mg0_input_current));
    mg0_input_voltage = unpack_right_shift_u32(src_p[4], 0u, 0xffu);
    mg0_input_voltage |= unpack_left_shift_u32(src_p[5], 8u, 0xffu);
    mg0_input_voltage |= unpack_left_shift_u32(src_p[6], 16u, 0xffu);
    mg0_input_voltage |= unpack_left_shift_u32(src_p[7], 24u, 0xffu);
    memcpy(&dst_p->mg0_input_voltage, &mg0_input_voltage, sizeof(dst_p->mg0_input_voltage));

    return (0);
}

int mppt_mg0_status_init(struct mppt_mg0_status_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct mppt_mg0_status_t));

    return 0;
}

float mppt_mg0_status_mg0_input_current_encode(double value)
{
    return (float)(value);
}

double mppt_mg0_status_mg0_input_current_decode(float value)
{
    return ((double)value);
}

bool mppt_mg0_status_mg0_input_current_is_in_range(float value)
{
    return ((value >= 0.0f) && (value <= 10000.0f));
}

float mppt_mg0_status_mg0_input_voltage_encode(double value)
{
    return (float)(value);
}

double mppt_mg0_status_mg0_input_voltage_decode(float value)
{
    return ((double)value);
}

bool mppt_mg0_status_mg0_input_voltage_is_in_range(float value)
{
    return ((value >= 0.0f) && (value <= 120.0f));
}

int mppt_mg1_status_pack(
    uint8_t *dst_p,
    const struct mppt_mg1_status_t *src_p,
    size_t size)
{
    uint32_t mg1_input_current;
    uint32_t mg1_input_voltage;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    memcpy(&mg1_input_current, &src_p->mg1_input_current, sizeof(mg1_input_current));
    dst_p[0] |= pack_left_shift_u32(mg1_input_current, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(mg1_input_current, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(mg1_input_current, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(mg1_input_current, 24u, 0xffu);
    memcpy(&mg1_input_voltage, &src_p->mg1_input_voltage, sizeof(mg1_input_voltage));
    dst_p[4] |= pack_left_shift_u32(mg1_input_voltage, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(mg1_input_voltage, 8u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(mg1_input_voltage, 16u, 0xffu);
    dst_p[7] |= pack_right_shift_u32(mg1_input_voltage, 24u, 0xffu);

    return (8);
}

int mppt_mg1_status_unpack(
    struct mppt_mg1_status_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t mg1_input_current;
    uint32_t mg1_input_voltage;

    if (size < 8u) {
        return (-EINVAL);
    }

    mg1_input_current = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    mg1_input_current |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    mg1_input_current |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    mg1_input_current |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    memcpy(&dst_p->mg1_input_current, &mg1_input_current, sizeof(dst_p->mg1_input_current));
    mg1_input_voltage = unpack_right_shift_u32(src_p[4], 0u, 0xffu);
    mg1_input_voltage |= unpack_left_shift_u32(src_p[5], 8u, 0xffu);
    mg1_input_voltage |= unpack_left_shift_u32(src_p[6], 16u, 0xffu);
    mg1_input_voltage |= unpack_left_shift_u32(src_p[7], 24u, 0xffu);
    memcpy(&dst_p->mg1_input_voltage, &mg1_input_voltage, sizeof(dst_p->mg1_input_voltage));

    return (0);
}

int mppt_mg1_status_init(struct mppt_mg1_status_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct mppt_mg1_status_t));

    return 0;
}

float mppt_mg1_status_mg1_input_current_encode(double value)
{
    return (float)(value);
}

double mppt_mg1_status_mg1_input_current_decode(float value)
{
    return ((double)value);
}

bool mppt_mg1_status_mg1_input_current_is_in_range(float value)
{
    return ((value >= 0.0f) && (value <= 10000.0f));
}

float mppt_mg1_status_mg1_input_voltage_encode(double value)
{
    return (float)(value);
}

double mppt_mg1_status_mg1_input_voltage_decode(float value)
{
    return ((double)value);
}

bool mppt_mg1_status_mg1_input_voltage_is_in_range(float value)
{
    return ((value >= 0.0f) && (value <= 120.0f));
}

int mppt_mg0_output_voltage_input_power_pack(
    uint8_t *dst_p,
    const struct mppt_mg0_output_voltage_input_power_t *src_p,
    size_t size)
{
    uint32_t mg0_input_power;
    uint32_t mg0_output_voltage;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    memcpy(&mg0_output_voltage, &src_p->mg0_output_voltage, sizeof(mg0_output_voltage));
    dst_p[0] |= pack_left_shift_u32(mg0_output_voltage, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(mg0_output_voltage, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(mg0_output_voltage, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(mg0_output_voltage, 24u, 0xffu);
    memcpy(&mg0_input_power, &src_p->mg0_input_power, sizeof(mg0_input_power));
    dst_p[4] |= pack_left_shift_u32(mg0_input_power, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(mg0_input_power, 8u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(mg0_input_power, 16u, 0xffu);
    dst_p[7] |= pack_right_shift_u32(mg0_input_power, 24u, 0xffu);

    return (8);
}

int mppt_mg0_output_voltage_input_power_unpack(
    struct mppt_mg0_output_voltage_input_power_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t mg0_input_power;
    uint32_t mg0_output_voltage;

    if (size < 8u) {
        return (-EINVAL);
    }

    mg0_output_voltage = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    mg0_output_voltage |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    mg0_output_voltage |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    mg0_output_voltage |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    memcpy(&dst_p->mg0_output_voltage, &mg0_output_voltage, sizeof(dst_p->mg0_output_voltage));
    mg0_input_power = unpack_right_shift_u32(src_p[4], 0u, 0xffu);
    mg0_input_power |= unpack_left_shift_u32(src_p[5], 8u, 0xffu);
    mg0_input_power |= unpack_left_shift_u32(src_p[6], 16u, 0xffu);
    mg0_input_power |= unpack_left_shift_u32(src_p[7], 24u, 0xffu);
    memcpy(&dst_p->mg0_input_power, &mg0_input_power, sizeof(dst_p->mg0_input_power));

    return (0);
}

int mppt_mg0_output_voltage_input_power_init(struct mppt_mg0_output_voltage_input_power_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct mppt_mg0_output_voltage_input_power_t));

    return 0;
}

float mppt_mg0_output_voltage_input_power_mg0_output_voltage_encode(double value)
{
    return (float)(value);
}

double mppt_mg0_output_voltage_input_power_mg0_output_voltage_decode(float value)
{
    return ((double)value);
}

bool mppt_mg0_output_voltage_input_power_mg0_output_voltage_is_in_range(float value)
{
    return ((value >= 0.0f) && (value <= 200.0f));
}

float mppt_mg0_output_voltage_input_power_mg0_input_power_encode(double value)
{
    return (float)(value);
}

double mppt_mg0_output_voltage_input_power_mg0_input_power_decode(float value)
{
    return ((double)value);
}

bool mppt_mg0_output_voltage_input_power_mg0_input_power_is_in_range(float value)
{
    return ((value >= 0.0f) && (value <= 1200000.0f));
}

int mppt_mg1_output_voltage_input_power_pack(
    uint8_t *dst_p,
    const struct mppt_mg1_output_voltage_input_power_t *src_p,
    size_t size)
{
    uint32_t mg1_input_power;
    uint32_t mg1_output_voltage;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    memcpy(&mg1_output_voltage, &src_p->mg1_output_voltage, sizeof(mg1_output_voltage));
    dst_p[0] |= pack_left_shift_u32(mg1_output_voltage, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(mg1_output_voltage, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(mg1_output_voltage, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(mg1_output_voltage, 24u, 0xffu);
    memcpy(&mg1_input_power, &src_p->mg1_input_power, sizeof(mg1_input_power));
    dst_p[4] |= pack_left_shift_u32(mg1_input_power, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(mg1_input_power, 8u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(mg1_input_power, 16u, 0xffu);
    dst_p[7] |= pack_right_shift_u32(mg1_input_power, 24u, 0xffu);

    return (8);
}

int mppt_mg1_output_voltage_input_power_unpack(
    struct mppt_mg1_output_voltage_input_power_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t mg1_input_power;
    uint32_t mg1_output_voltage;

    if (size < 8u) {
        return (-EINVAL);
    }

    mg1_output_voltage = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    mg1_output_voltage |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    mg1_output_voltage |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    mg1_output_voltage |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    memcpy(&dst_p->mg1_output_voltage, &mg1_output_voltage, sizeof(dst_p->mg1_output_voltage));
    mg1_input_power = unpack_right_shift_u32(src_p[4], 0u, 0xffu);
    mg1_input_power |= unpack_left_shift_u32(src_p[5], 8u, 0xffu);
    mg1_input_power |= unpack_left_shift_u32(src_p[6], 16u, 0xffu);
    mg1_input_power |= unpack_left_shift_u32(src_p[7], 24u, 0xffu);
    memcpy(&dst_p->mg1_input_power, &mg1_input_power, sizeof(dst_p->mg1_input_power));

    return (0);
}

int mppt_mg1_output_voltage_input_power_init(struct mppt_mg1_output_voltage_input_power_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct mppt_mg1_output_voltage_input_power_t));

    return 0;
}

float mppt_mg1_output_voltage_input_power_mg1_output_voltage_encode(double value)
{
    return (float)(value);
}

double mppt_mg1_output_voltage_input_power_mg1_output_voltage_decode(float value)
{
    return ((double)value);
}

bool mppt_mg1_output_voltage_input_power_mg1_output_voltage_is_in_range(float value)
{
    return ((value >= 0.0f) && (value <= 200.0f));
}

float mppt_mg1_output_voltage_input_power_mg1_input_power_encode(double value)
{
    return (float)(value);
}

double mppt_mg1_output_voltage_input_power_mg1_input_power_decode(float value)
{
    return ((double)value);
}

bool mppt_mg1_output_voltage_input_power_mg1_input_power_is_in_range(float value)
{
    return ((value >= 0.0f) && (value <= 1200000.0f));
}

int mppt_mg0_pcbmosfet_temperature_pack(
    uint8_t *dst_p,
    const struct mppt_mg0_pcbmosfet_temperature_t *src_p,
    size_t size)
{
    uint16_t mg0_mosfet_temperature;
    uint16_t mg0_pcb_temperature;

    if (size < 4u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 4);

    mg0_pcb_temperature = (uint16_t)src_p->mg0_pcb_temperature;
    dst_p[0] |= pack_left_shift_u16(mg0_pcb_temperature, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(mg0_pcb_temperature, 8u, 0xffu);
    mg0_mosfet_temperature = (uint16_t)src_p->mg0_mosfet_temperature;
    dst_p[2] |= pack_left_shift_u16(mg0_mosfet_temperature, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(mg0_mosfet_temperature, 8u, 0xffu);

    return (4);
}

int mppt_mg0_pcbmosfet_temperature_unpack(
    struct mppt_mg0_pcbmosfet_temperature_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t mg0_mosfet_temperature;
    uint16_t mg0_pcb_temperature;

    if (size < 4u) {
        return (-EINVAL);
    }

    mg0_pcb_temperature = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    mg0_pcb_temperature |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->mg0_pcb_temperature = (int16_t)mg0_pcb_temperature;
    mg0_mosfet_temperature = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    mg0_mosfet_temperature |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->mg0_mosfet_temperature = (int16_t)mg0_mosfet_temperature;

    return (0);
}

int mppt_mg0_pcbmosfet_temperature_init(struct mppt_mg0_pcbmosfet_temperature_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct mppt_mg0_pcbmosfet_temperature_t));

    return 0;
}

int16_t mppt_mg0_pcbmosfet_temperature_mg0_pcb_temperature_encode(double value)
{
    return (int16_t)(value / 0.01);
}

double mppt_mg0_pcbmosfet_temperature_mg0_pcb_temperature_decode(int16_t value)
{
    return ((double)value * 0.01);
}

bool mppt_mg0_pcbmosfet_temperature_mg0_pcb_temperature_is_in_range(int16_t value)
{
    return ((value >= -4000) && (value <= 8000));
}

int16_t mppt_mg0_pcbmosfet_temperature_mg0_mosfet_temperature_encode(double value)
{
    return (int16_t)(value / 0.01);
}

double mppt_mg0_pcbmosfet_temperature_mg0_mosfet_temperature_decode(int16_t value)
{
    return ((double)value * 0.01);
}

bool mppt_mg0_pcbmosfet_temperature_mg0_mosfet_temperature_is_in_range(int16_t value)
{
    return ((value >= -4000) && (value <= 8000));
}

int mppt_mg1_pcbmosfet_temperature_pack(
    uint8_t *dst_p,
    const struct mppt_mg1_pcbmosfet_temperature_t *src_p,
    size_t size)
{
    uint16_t mg1_mosfet_temperature;
    uint16_t mg1_pcb_temperature;

    if (size < 4u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 4);

    mg1_pcb_temperature = (uint16_t)src_p->mg1_pcb_temperature;
    dst_p[0] |= pack_left_shift_u16(mg1_pcb_temperature, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(mg1_pcb_temperature, 8u, 0xffu);
    mg1_mosfet_temperature = (uint16_t)src_p->mg1_mosfet_temperature;
    dst_p[2] |= pack_left_shift_u16(mg1_mosfet_temperature, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(mg1_mosfet_temperature, 8u, 0xffu);

    return (4);
}

int mppt_mg1_pcbmosfet_temperature_unpack(
    struct mppt_mg1_pcbmosfet_temperature_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t mg1_mosfet_temperature;
    uint16_t mg1_pcb_temperature;

    if (size < 4u) {
        return (-EINVAL);
    }

    mg1_pcb_temperature = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    mg1_pcb_temperature |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->mg1_pcb_temperature = (int16_t)mg1_pcb_temperature;
    mg1_mosfet_temperature = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    mg1_mosfet_temperature |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->mg1_mosfet_temperature = (int16_t)mg1_mosfet_temperature;

    return (0);
}

int mppt_mg1_pcbmosfet_temperature_init(struct mppt_mg1_pcbmosfet_temperature_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct mppt_mg1_pcbmosfet_temperature_t));

    return 0;
}

int16_t mppt_mg1_pcbmosfet_temperature_mg1_pcb_temperature_encode(double value)
{
    return (int16_t)(value / 0.01);
}

double mppt_mg1_pcbmosfet_temperature_mg1_pcb_temperature_decode(int16_t value)
{
    return ((double)value * 0.01);
}

bool mppt_mg1_pcbmosfet_temperature_mg1_pcb_temperature_is_in_range(int16_t value)
{
    return ((value >= -4000) && (value <= 8000));
}

int16_t mppt_mg1_pcbmosfet_temperature_mg1_mosfet_temperature_encode(double value)
{
    return (int16_t)(value / 0.01);
}

double mppt_mg1_pcbmosfet_temperature_mg1_mosfet_temperature_decode(int16_t value)
{
    return ((double)value * 0.01);
}

bool mppt_mg1_pcbmosfet_temperature_mg1_mosfet_temperature_is_in_range(int16_t value)
{
    return ((value >= -4000) && (value <= 8000));
}
